// <auto-generated />
using System;
using JobPortal.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobPortal.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191027014344_Relations")]
    partial class Relations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobPortal.Web.Data.Entities.AcademicProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("AcademicPrograms");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Remarks");

                    b.HasKey("Id");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Logo");

                    b.Property<string>("NIT")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Remarks");

                    b.Property<int?>("VacanciesId");

                    b.HasKey("Id");

                    b.HasIndex("VacanciesId");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.InterviewMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgendaId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Remarks");

                    b.Property<int?>("VancancyPostulationsId");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.HasIndex("VancancyPostulationsId");

                    b.ToTable("InterviewMeetings");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.MeetingState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InterviewMeetingId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("InterviewMeetingId");

                    b.ToTable("MeetingStates");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.PostulationStates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("VancancyPostulationsId");

                    b.HasKey("Id");

                    b.HasIndex("VancancyPostulationsId");

                    b.ToTable("PostulationStates");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.UserITM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AcademicProgramId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Semester");

                    b.Property<int?>("UserTypeId");

                    b.HasKey("Id");

                    b.HasIndex("AcademicProgramId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("UserITMs");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.Vacancies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.VacancyTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("VacanciesId");

                    b.HasKey("Id");

                    b.HasIndex("VacanciesId");

                    b.ToTable("VacancyTypes");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.VancancyPostulations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int?>("EnterpriseId");

                    b.Property<int?>("userITMId");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("userITMId");

                    b.ToTable("VancancyPostulations");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.Enterprise", b =>
                {
                    b.HasOne("JobPortal.Web.Data.Entities.Vacancies")
                        .WithMany("Enterprises")
                        .HasForeignKey("VacanciesId");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.InterviewMeeting", b =>
                {
                    b.HasOne("JobPortal.Web.Data.Entities.Agenda")
                        .WithMany("InterviewMeetings")
                        .HasForeignKey("AgendaId");

                    b.HasOne("JobPortal.Web.Data.Entities.VancancyPostulations", "VancancyPostulations")
                        .WithMany("InterviewMeetings")
                        .HasForeignKey("VancancyPostulationsId");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.MeetingState", b =>
                {
                    b.HasOne("JobPortal.Web.Data.Entities.InterviewMeeting", "InterviewMeeting")
                        .WithMany("MeetingStates")
                        .HasForeignKey("InterviewMeetingId");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.PostulationStates", b =>
                {
                    b.HasOne("JobPortal.Web.Data.Entities.VancancyPostulations", "VancancyPostulations")
                        .WithMany("PostulationStates")
                        .HasForeignKey("VancancyPostulationsId");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.UserITM", b =>
                {
                    b.HasOne("JobPortal.Web.Data.Entities.AcademicProgram", "AcademicProgram")
                        .WithMany("userITMs")
                        .HasForeignKey("AcademicProgramId");

                    b.HasOne("JobPortal.Web.Data.Entities.UserType", "UserType")
                        .WithMany("userITMs")
                        .HasForeignKey("UserTypeId");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.VacancyTypes", b =>
                {
                    b.HasOne("JobPortal.Web.Data.Entities.Vacancies", "Vacancies")
                        .WithMany("VacancyTypes")
                        .HasForeignKey("VacanciesId");
                });

            modelBuilder.Entity("JobPortal.Web.Data.Entities.VancancyPostulations", b =>
                {
                    b.HasOne("JobPortal.Web.Data.Entities.Enterprise")
                        .WithMany("VancancyPostulations")
                        .HasForeignKey("EnterpriseId");

                    b.HasOne("JobPortal.Web.Data.Entities.UserITM", "userITM")
                        .WithMany("VancancyPostulations")
                        .HasForeignKey("userITMId");
                });
#pragma warning restore 612, 618
        }
    }
}
